# .github/workflows/test.yml

name: Run Spring Boot Tests

on:
  pull_request:
    branches: [ "main" ]  # 🔥 main 브랜치로 PR 생성되면 작동

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: ./mvnw test  # 또는 mvn test
